Add support for a password-no-prompt flag
couchbaselabs/couchbase-shell pull request #257
Opened 2023-07-31 08:41 UTC by chvck

2023-07-31 08:41 UTC, chvck commented
I don't love this but also cannot find another approach.

2023-09-13 21:00 UTC, ingenthr reviewed
So, the canonical way to do this in a CLI tool is to have two options:

Ask me for the password at stdin:
```
-p -
```

Use the string "foobar" as a password:
```
-p foobar
```

Then you can require -p as an argument and if it's elided, error out.  

Seems like it'd be a better approach.  Also, it's sometimes nice to be able to specify password is in a file.  This is a security consideration, since on UNIX users can see the command line flags from other users.

2023-09-13 21:03 UTC, ingenthr commented
Related: https://www.netmeister.org/blog/passing-passwords.html

2023-09-14 18:00 UTC, ingenthr commented on src/cli_options.rs
> +                "use to trigger a prompt to specify a password to use for authentication",
I think with the change, this line isn't quite right, is it?  It's provide the password or prompt it `-` is specified.

2023-09-18 20:26 UTC, ingenthr requested changes
Note on the help there…

2023-09-19 16:38 UTC, ingenthr approved these changes

2023-09-20 07:39 UTC, merged